<html>
<body>
<pre>
<h1>Build Log</h1>
<h3>
--------------------Configuration: CONTOR - Win32 (WCE ARMV4) Release--------------------
</h3>
<h3>Command Lines</h3>
Creating temporary file "C:\DOCUME~1\HURAKH~1\LOCALS~1\Temp\RSP113.tmp" with contents
[
/nologo /W3 /D "ARM" /D "_ARM_" /D "ARMV4" /D UNDER_CE=420 /D _WIN32_WCE=420 /D "WCE_PLATFORM_MC3000C42B" /D "UNICODE" /D "_UNICODE" /D "NDEBUG" /D "_AFXDLL" /Fp"ARMV4Rel/CONTOR.pch" /Yu"stdafx.h" /Fo"ARMV4Rel/" /O2 /MC /c 
"C:\My Documents\AdoSample\CONTOR\MoreSettingsDlg.cpp"
]
Creating command line "clarm.exe @C:\DOCUME~1\HURAKH~1\LOCALS~1\Temp\RSP113.tmp" 
Creating temporary file "C:\DOCUME~1\HURAKH~1\LOCALS~1\Temp\RSP114.tmp" with contents
[
ScnAPI32.lib /nologo /base:"0x00010000" /stack:0x10000,0x1000 /entry:"wWinMainCRTStartup" /incremental:no /pdb:"ARMV4Rel/CONTOR.pdb" /out:"ARMV4Rel/CONTOR.exe" /subsystem:windowsce,4.20 /align:"4096" /MACHINE:ARM 
".\ARMV4Rel\ado.obj"
".\ARMV4Rel\ADSearchDlg.obj"
".\ARMV4Rel\AlertBoxDlg.obj"
".\ARMV4Rel\CONTOR.obj"
".\ARMV4Rel\CONTORDlg.obj"
".\ARMV4Rel\CustomersADSortedDlg.obj"
".\ARMV4Rel\CustomersInfoDlg.obj"
".\ARMV4Rel\CustomersMoreinfoDlg.obj"
".\ARMV4Rel\EnterSerialDlg.obj"
".\ARMV4Rel\FilesReadyDlg.obj"
".\ARMV4Rel\HasNotTransferedDataDlg.obj"
".\ARMV4Rel\MoreSettingsDlg.obj"
".\ARMV4Rel\NotFoundDlg.obj"
".\ARMV4Rel\NotFoundPathDlg.obj"
".\ARMV4Rel\OperatorsPathDlg.obj"
".\ARMV4Rel\PathSelectDlg.obj"
".\ARMV4Rel\PersianSupport.obj"
".\ARMV4Rel\QuestionBoxDlg.obj"
".\ARMV4Rel\ReadDataProgressDlg.obj"
".\ARMV4Rel\ReadValueDlg.obj"
".\ARMV4Rel\ReportErrDlg.obj"
".\ARMV4Rel\ScanDlg.obj"
".\ARMV4Rel\SearchMethodSelDlg.obj"
".\ARMV4Rel\SearchSerialDlg.obj"
".\ARMV4Rel\SearchSubDlg.obj"
".\ARMV4Rel\SettingsDlg.obj"
".\ARMV4Rel\SettingsPassDlg.obj"
".\ARMV4Rel\StatsDlg.obj"
".\ARMV4Rel\StdAfx.obj"
".\ARMV4Rel\UniButton.obj"
".\ARMV4Rel\WriteDataProgressDlg.obj"
".\ARMV4Rel\CONTOR.res"
]
Creating command line "link.exe @C:\DOCUME~1\HURAKH~1\LOCALS~1\Temp\RSP114.tmp"
<h3>Output Window</h3>
Compiling...
MoreSettingsDlg.cpp
Linking...




<h3>Results</h3>
CONTOR.exe - 0 error(s), 0 warning(s)
</pre>
</body>
</html>
