//{{NO_DEPENDENCIES}}
// Microsoft eMbedded Visual C++ generated include file.
// Used by CONTOR.rc
//
#define IDC_READDATFILE                 2
#define IDC_NEXT                        2
#define IDC_METHOD1                     2
#define IDC_SEARCH                      2
#define IDC_SOFTSCAN                    2
#define IDC_BACKUPNOW4ME                2
#define IDC_METERREADING                3
#define IDC_PREV                        3
#define IDC_DELETE                      3
#define IDC_METHOD2                     3
#define IDC_OTHERSETTINGS               3
#define IDC_MORE                        4
#define IDC_METHOD3                     4
#define IDC_METERREADING2               4
#define IDC_SHOWINFORMATON              4
#define IDC_SELECT                      5
#define IDC_METHOD4                     5
#define IDC_CHANGEMETHEOD               6
#define IDC_METHOD5                     6
#define IDC_SETTINGS                    7
#define IDC_ERR                         8
#define IDC_SELPATH                     9
#define IDC_READDATATIMER               101
#define IDD_CONTOR_DIALOG               102
#define IDC_WRITEDATATIMER              102
#define IDR_MAINFRAME                   128
#define IDD_READPROGRESS                129
#define IDD_CUSTOMERS_ADSORTED          130
#define IDD_CUSTOMERS_MOREINFO          131
#define IDD_CUSTOMERS_READ              132
#define IDD_CUSTOMERS_ERROR             133
#define IDD_SEARCH_SELTOOL              134
#define IDD_CUSTOMERS_SCAN              135
#define IDD_CUSTOMERS_INFO              136
#define IDD_CUSTOMERS_SEARCHSERIAL      137
#define IDD_CUSTOMERS_SEARCHSUB         138
#define IDD_CUSTOMERS_SEARCHAD          139
#define IDD_NOTFOUND                    140
#define IDD_CUSTOMERS_STATS             141
#define IDD_OPERATOR_PASS               142
#define IDD_WRITEPROGRESS               143
#define IDD_FILESREADY                  144
#define IDD_NOTTRANSFRED                145
#define IDB_METERBITMAP                 146
#define IDB_BITMAP_CLOSE                149
#define IDB_BITMAP_CLOSED               152
#define IDB_METERBITMAPD                154
#define IDB_BITMAP_BKGND                155
#define IDD_CONTOR_SETTINGS             161
#define IDD_SELPATH                     162
#define IDD_NOTFOUNDPATH                163
#define IDD_GETSERIAL                   164
#define IDD_ALERT                       165
#define IDD_SETTINGS_PASS               166
#define IDD_MORESETTINGS                167
#define IDD_QUESTION                    168
#define IDC_READPROGRESS                1001
#define IDC_SFRAME                      1002
#define IDC_SSUBTITLE                   1003
#define IDC_SSUB                        1004
#define IDC_SSUBTITLE2                  1004
#define IDC_SNAMTITLE                   1005
#define IDC_SFAMTITLE                   1006
#define IDC_SADTITLE                    1007
#define IDC_SADDRESS                    1007
#define IDC_SSERTITLE                   1008
#define IDC_SADRTITLE                   1008
#define IDC_SNAM                        1009
#define IDC_SADRTITLE2                  1009
#define IDC_SFAM                        1010
#define IDC_SPREVDTITLE                 1010
#define IDC_SAD                         1011
#define IDC_SSER                        1012
#define IDC_SPREVCTITLE                 1013
#define IDC_SNOWTITLE                   1014
#define IDC_SCONTITLE                   1015
#define IDC_ENOW                        1016
#define IDC_SCON                        1017
#define IDC_EPASS                       1017
#define IDC_SPREVC                      1018
#define IDC_SPREVD                      1019
#define IDC_ENTER                       1020
#define IDC_ERROR                       1021
#define IDC_READ                        1021
#define IDC_NEXTPAGE                    1022
#define IDC_PREVPAGE                    1023
#define IDC_CHECK1                      1024
#define IDC_CERR01                      1024
#define IDC_CERR2                       1025
#define IDC_CERR02                      1025
#define IDC_ESEARCH                     1025
#define IDC_CERR3                       1026
#define IDC_CERR03                      1026
#define IDC_ESEARCHTITLE                1026
#define IDC_CERR4                       1027
#define IDC_CERR04                      1027
#define IDC_SDATE                       1027
#define IDC_CERR5                       1028
#define IDC_CERR05                      1028
#define IDC_SSTAT                       1028
#define IDC_SNOTREAD                    1029
#define IDC_STODAY                      1030
#define IDC_SOPCODETITLE                1031
#define IDC_SFDATE                      1031
#define IDC_SPASSTITLE                  1032
#define IDC_EOPCODE                     1033
#define IDC_WRITEPROGRESS               1034
#define IDC_RGOTO                       1035
#define IDC_SCOMMENT2                   1035
#define IDC_RGOTO2                      1036
#define IDC_CPATHCOMBO                  1036
#define IDC_SCOMMENT3                   1036
#define IDC_RGOTO3                      1037
#define IDC_PATHBEGIN                   1037
#define IDC_PATHEND                     1038
#define IDC_SPATHSELECTTITLE            1039
#define IDC_SCOMMENT                    1040
#define IDC_ESERIAL                     1041

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        169
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1042
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
